#ifndef _SETTINGS_H
#define _SETTINGS_H

const char* const DATABASE_FILE_NAME = "Test_DB.txt";

const int MAX_SPEAK_BUFFER_LEN = 4096;
const int MAX_STR_LEN          = 100;
const int MAX_CMD_LEN          = 310;

typedef char TreeElem_t[MAX_STR_LEN];

enum CodeError
{
    NO_ERR,

    FILE_NOT_OPENED_ERR,
    FILLING_FSTAT_ERR,
    WRONG_BUFSIZE_ERR,

    SYSTEM_CALL_ERR,

    DATABASE_READ_END_ERR,
    DATABASE_READ_LEFT_ERR,
    DATABASE_READ_RIGHT_ERR,

    NO_MEM_FOR_TREE_ERR,
    TREE_NOT_INITED_ERR,

    NULL_TREE_TO_SAVE_ERR,
    TREE_ALREADY_INITED_ERR,
    TREE_ERROR,

    UNKNOWN_AKINATOR_MODE_ERR,
};

#endif
